apiVersion: v1
kind: ConfigMap
metadata:
  namespace: cloud-deployments-web
  name: cloud-deployments-configmap
data:
  APP_NAME: "Cloud Deployments Kubernetes"
  APP_ENV: "production"
  APP_DEBUG: "true"
  APP_TIMEZONE: "Europe/Amsterdam"
  APP_URL: "https://cloud-deployments.dev"
  ASSET_URL: "https://cloud-deployments.dev"
  APP_VERSION: "v2.2.1-dev"

  APP_LOCALE: "nl"
  APP_FALLBACK_LOCALE: "en"
  APP_FAKER_LOCALE: "en_US"

  APP_MAINTENANCE_DRIVER: "file"

  BCRYPT_ROUNDS: "12"

  LOG_CHANNEL: "daily"
  LOG_STACK: "single"
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: "debug"

  DB_CONNECTION: "mysql"
  DB_HOST: "mariadb"
  DB_PORT: "3306"
  DB_DATABASE: "laravel"
  DB_USERNAME: "laravel"
  DB_PASSWORD: "laravel"

  SESSION_DRIVER: "database"
  SESSION_LIFETIME: "720"
  SESSION_ENCRYPT: "true"
  SESSION_PATH: "/"
  SESSION_DOMAIN: "null"

  BROADCAST_CONNECTION: "reverb"
  FILESYSTEM_DISK: "local"
  QUEUE_CONNECTION: "redis"

  CACHE_STORE: "database"
  CACHE_PREFIX: "cd"

  REDIS_HOST: "redis"
  REDIS_PASSWORD: null
  REDIS_PORT: "6379"

  POSTMARK_TOKEN: "f7d85d1f-aa24-447a-a679-742f06ad7792"
  MAIL_MAILER: "smtp"
  MAIL_HOST: "smtp.postmarkapp.com"
  MAIL_PORT: "2525"
  MAIL_USERNAME: "${POSTMARK_TOKEN}"
  MAIL_PASSWORD: "${POSTMARK_TOKEN}"
  MAIL_ENCRYPTION: "tls"
  MAIL_FROM_ADDRESS: "no-reply@cloud-deployments.dev"
  MAIL_FROM_NAME: "${APP_NAME}"

  VITE_APP_NAME: "${APP_NAME}"

  REVERB_APP_ID: "715092"
  REVERB_APP_KEY: "hrpywjpgovxelracwt2v"
  REVERB_HOST: "https://cloud-deployments.dev"
  REVERB_PORT: "8080"
  REVERB_SCHEME: "http"

  VITE_REVERB_APP_KEY: "${REVERB_APP_KEY}"
  VITE_REVERB_HOST: "${REVERB_HOST}"
  VITE_REVERB_PORT: "${REVERB_PORT}"
  VITE_REVERB_SCHEME: "${REVERB_SCHEME}"
