apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cloud-deployments-web
  name: cloud-deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-deployments
  template:
    metadata:
      labels:
        app: cloud-deployments
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: app-storage
          persistentVolumeClaim:
            claimName: cloud-deployments-pvc-storage
        - name: shared-public
          emptyDir: {}
        - name: logs
          emptyDir: {}
        - name: cache
          emptyDir: {}
        - name: testing
          emptyDir: {}
        - name: sessions
          emptyDir: {}
        - name: views
          emptyDir: {}
      securityContext:
        fsGroup: 82
      initContainers:
        - name: copy-build-files
          image: noahdev123/cloud-deployments:latest
          command: ["/bin/sh", "-c", "cp -r /var/www/html/public/* /shared-public/"]
          volumeMounts:
            - name: shared-public
              mountPath: /shared-public
      containers:
        - name: fpm
          image: noahdev123/cloud-deployments:latest
          resources:
            requests:
              cpu: 250m
              memory: 128M
            limits:
              cpu: 500m
              memory: 256M
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: app-storage
              mountPath: /var/www/html/storage
            - name: shared-public
              mountPath: /var/www/html/public
            - name: logs
              mountPath: /var/www/html/storage/logs
            - name: cache
              mountPath: /var/www/html/storage/framework/cache
            - name: sessions
              mountPath: /var/www/html/storage/framework/sessions
            - name: views
              mountPath: /var/www/html/storage/framework/views
            - name: testing
              mountPath: /var/www/html/storage/framework/testing
          envFrom:
            - configMapRef:
                name: cloud-deployments-configmap
            - secretRef:
                name: cloud-deployments-secrets
        - name: horizon
          image: noahdev123/cloud-deployments:latest
          envFrom:
            - configMapRef:
                name: cloud-deployments-configmap
            - secretRef:
                name: cloud-deployments-secrets
          command: [ "php", "artisan", "horizon" ]
        - name: scheduler
          image: noahdev123/cloud-deployments:latest
          envFrom:
            - configMapRef:
                name: cloud-deployments-configmap
            - secretRef:
                name: cloud-deployments-secrets
          command: [ "php", "artisan", "schedule:work" ]
        - name: reverb
          image: noahdev123/cloud-deployments:latest
          resources:
            requests:
              cpu: 200m
              memory: 128M
            limits:
              cpu: 400m
              memory: 256M
          envFrom:
            - configMapRef:
                name: cloud-deployments-configmap
            - secretRef:
                name: cloud-deployments-secrets
          command: [ "php", "artisan", "reverb:start", "--host=0.0.0.0", "--port=8080" ]
        - name: nginx
          image: noahdev123/cloud-deployments-nginx:latest
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: false
            - name: shared-public
              mountPath: /var/www/html/public
          resources:
            requests:
              cpu: 250m
              memory: 128M
            limits:
              cpu: 500m
              memory: 256M
          ports:
            - containerPort: 80
