---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  namespace: cloud-deployments-web
  name: cloud-deployments
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cloud-deployments
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
