apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: cloud-deployments-web
  name: cloud-deployments-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - cloud-deployments.dev
      secretName: cloud-deployments-tls
  rules:
    - host: cloud-deployments.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloud-deployments
                port:
                  number: 9000
