apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloud-deployments-mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: cloud-deployments-sc
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mysql/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-deployments-mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
