apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: cloud-deployments-web
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql/cloud-deployments
