apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloud-deployments-pv-storage
  namespace: cloud-deployments-web
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/www/cloud-deployments.dev/storage
  storageClassName: cloud-deployments-sc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloud-deployments-pv-public
  namespace: cloud-deployments-web
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/www/cloud-deployments.dev/public
  storageClassName: cloud-deployments-sc
