apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-deployments-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: cloud-deployments-sc
