apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloud-deployments-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/www/cloud-deployments.dev/storage"
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
