apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: cloud-deployments-web
  name: scheduler
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scheduled
              image: noahdev123/cloud-deployments:latest
              envFrom:
                - configMapRef:
                    name: cloud-deployments-configmap
                - secretRef:
                    name: cloud-deployments-secrets
              command:
                - "php"
              args:
                - "artisan"
                - "schedule:run"
          restartPolicy: OnFailure
