apiVersion: v1
kind: Service
metadata:
  namespace: cloud-deployments-web
  name: cloud-deployments-nginx
  labels:
    app: cloud-deployments-nginx
spec:
  selector:
    app: cloud-deployments-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
